# Generated by Django 3.1.5 on 2022-03-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Predmeti',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Razred',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Prvi Razred', 'prvi'), ('Drugi Razred', 'drugi'), ('Treci Razred', 'treci'), ('Cetvrti Razred', 'cetvrti')], max_length=50)),
                ('predmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razredi', to='main.predmet')),
            ],
            options={
                'verbose_name_plural': 'Razredi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('predmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predmetni_naslov', to='main.predmet')),
                ('razred', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razredni_naslov', to='main.razred')),
            ],
            options={
                'verbose_name_plural': 'Naslovi',
                'ordering': ['id'],
            },
        ),
    ]
