# Generated by Django 3.1.5 on 2022-03-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_naslov_razred'),
    ]

    operations = [
        migrations.AddField(
            model_name='naslov',
            name='razred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razredni_naslov', to='main.razred'),
        ),
    ]
